using System;
using System.Collections.Generic;

namespace AgeOfEmpiresLibrary
{
    public static class ResearchType
    {
        public static Research RESEARCH_ELITE_TARKAN = new Research(2, 45000, "Elite Tarkan", new Resources(0, 1000, 500, 0));
        public static Research RESEARCH_YEOMAN = new Research(3, 60000, "Yeoman", new Resources(0, 750, 450, 0));
        public static Research RESEARCH_EL_DORADO = new Research(4, 50000, "El Dorado", new Resources(0, 750, 450, 0));
        public static Research RESEARCH_FUROR_CELTICA = new Research(5, 50000, "Furor Celtica", new Resources(0, 750, 450, 0));
        public static Research RESEARCH_DRILL = new Research(6, 60000, "Drill", new Resources(0, 500, 450, 0));
        public static Research RESEARCH_MAHOUTS = new Research(7, 50000, "Mahouts", new Resources(0, 300, 300, 0));
        public static Research RESEARCH_TOWN_WATCH = new Research(8, 25000, "Town Watch", new Resources(0, 75, 0, 0));
        public static Research RESEARCH_ZEALOTRY = new Research(9, 50000, "Zealotry", new Resources(0, 750, 800, 0));
        public static Research RESEARCH_ARTILLERY = new Research(10, 40000, "Artillery", new Resources(0, 500, 450, 0));
        public static Research RESEARCH_CRENELLATIONS = new Research(11, 60000, "Crenellations", new Resources(0, 600, 400, 0));
        public static Research RESEARCH_CROP_ROTATION = new Research(12, 70000, "Crop Rotation", new Resources(250, 250, 0, 0));
        public static Research RESEARCH_HEAVY_PLOW = new Research(13, 40000, "Heavy Plow", new Resources(125, 125, 0, 0));
        public static Research RESEARCH_HEAVY_COLLAR = new Research(14, 20000, "Horse Collar", new Resources(75, 75, 0, 0));
        public static Research RESEARCH_GUILDS = new Research(15, 50000, "Guilds", new Resources(0, 300, 200, 0));
        public static Research RESEARCH_ANARCHY = new Research(16, 40000, "Anarchy", new Resources(0, 450, 250, 0));
        public static Research RESEARCH_BANKING = new Research(17, 70000, "Banking", new Resources(0, 300, 200, 0));
        public static Research RESEARCH_CARTOGRAPHY = new Research(19, 10000, "Cartography", new Resources(0, 0, 0, 0));
        public static Research RESEARCH_ATHEISM = new Research(21, 60000, "Atheism", new Resources(0, 500, 500, 0));
        public static Research RESEARCH_LOOM = new Research(22, 25000, "Loom", new Resources(0, 0, 50, 0));
        public static Research RESEARCH_COINAGE = new Research(23, 70000, "Coinage", new Resources(0, 200, 100, 0));
        public static Research RESEARCH_GARLAND_WARS = new Research(24, 60000, "Garland Wars", new Resources(0, 450, 750, 0));
        public static Research RESEARCH_ELITE_PLUMED_ARCHER = new Research(27, 45000, "Elite Plumed Archer", new Resources(1000, 700, 0, 0));
        public static Research RESEARCH_WAR_GALLEY = new Research(34, 50000, "War Galley", new  Resources(0, 230, 100, 0));
        public static Research RESEARCH_GALLEON = new Research(35, 65000, "Galleon", new Resources(0, 400, 315, 0));
        public static Research RESEARCH_CANNON_GALLEON = new Research(37, 50000, "Cannon Galleon", new Resources(500, 400, 0, 0));
        public static Research RESEARCH_HUSBANDRY = new Research(39, 40000, "Husbandry", new Resources(0, 250, 0, 0));
        public static Research RESEARCH_FAITH = new Research(45, 60000, "Faith", new Resources(0, 750, 1000, 0));
        public static Research RESEARCH_BLOCK_PRINTING = new Research(46, 60000, "Block Printing", new Resources(0, 0, 200, 0));
        public static Research RESEARCH_CHEMISTRY = new Research(47, 100000, "Chemistry", new Resources(0, 200, 200, 0));
        public static Research RESEARCH_CARAVAN = new Research(48, 40000, "Caravan", new Resources(0, 200, 200, 0));
        public static Research RESEARCH_BERSERKERGANG = new Research(49, 40000, "Berserkergang", new Resources(0, 850, 400, 0));
        public static Research RESEARCH_MASONARY = new Research(50, 50000, "Masonary", new Resources(175, 150, 0, 0));
        public static Research RESEARCH_ARCHITECTURE = new Research(51, 70000, "Architecture", new  Resources(200, 300, 0, 0));
        public static Research RESEARCH_ROCKETRY = new Research(52, 60000, "Rockery", new Resources(0, 600, 60, 0));
        public static Research RESEARCH_TREADMILL_CRANE = new Research(54, 50000, "Treadmill Crane", new Resources(200, 300, 0, 0));
        public static Research RESEARCH_GOLD_MINING = new Research(55, 30000, "Gold Mining", new Resources(75, 100, 0, 0));
        public static Research RESEARCH_KATAPARUTO = new Research(59, 60000, "Kataparuto", new Resources(0, 750, 400, 0));
        public static Research RESEARCH_ELITE_CONQUISTADOR = new Research(60, 60000, "Elite Conquistador", new Resources(0, 1200, 600, 0));
        public static Research RESEARCH_LOGISTICA = new Research(61, 50000, "Logistica", new Resources(0, 1000, 600, 0));
        public static Research RESEARCH_KEEP = new Research(63, 75000, "Keep", new Resources(350, 500, 0, 0));
        public static Research RESEARCH_BOMBARD_TOWER = new Research(64, 60000, "Bombard Tower", new Resources(400, 800, 0, 0));
        public static Research RESEARCH_GILLNETS = new Research(65, 45000, "Gillnets", new Resources(200, 150, 0, 0));
        public static Research RESEARCH_FORGING = new Research(67, 50000, "Forging", new Resources(0, 150, 0, 0));
        public static Research RESEARCH_IRON_CASTING = new Research(68, 75000, "Iron Casting", new Resources(0, 220, 120, 0));
        public static Research RESEARCH_SCALE_MAIL_ARMOR = new Research(74, 40000, "Scale Mail Armor", new Resources(0, 100, 0, 0));
        public static Research RESEARCH_BLAST_FURNACE = new Research(75, 100000, "Blast Furnace", new Resources(0, 275, 225, 0));
        public static Research RESEARCH_CHAIN_MAIL_ARMOR = new Research(76, 55000, "Chain Mail Armor", new Resources(0, 200, 100, 0));
        public static Research RESEARCH_PLATE_MAIL_ARMOR = new Research(77, 70000, "Plate Mail Armor", new Resources(0, 300, 150, 0));
        public static Research RESEARCH_PLATE_BARDING_ARMOR = new Research(80, 75000, "Plate Barding Armor", new Resources(0, 350, 200, 0));
        public static Research RESEARCH_SCALE_BARDING_ARMOR = new Research(81, 60000, "Scale Barding Armor", new Resources(0, 120, 0, 0));
        public static Research RESEARCH_CHAIN_BARDING_ARMOR = new Research(82, 25000, "Chain Barding Armor", new Resources(0, 250, 150, 0));
        public static Research RESEARCH_BEARDED_AXE = new Research(83, 60000, "Bearded Axe", new Resources(0, 400, 400, 0));
        public static Research RESEARCH_TRACKING = new Research(90, 35000, "Tracking", new Resources(0, 50, 0, 0));
        public static Research RESEARCH_BALLISTICS = new Research(93, 60000, "Ballistics", new Resources(300, 0, 175, 0));
        public static Research RESEARCH_CAPPED_RAM = new Research(96, 50000, "Capped Ram", new Resources(0, 300, 0, 0));
        public static Research RESEARCH_ELITE_SKIRMISHER = new Research(98, 50000, "Elite Skirmisher", new Resources(200, 0, 100, 0));
        public static Research RESEARCH_CROSSBOWMAN = new Research(100, 35000, "Crossbowman", new Resources(0, 125, 75, 0));
        public static Research RESEARCH_FEUDAL_AGE = new Research(101, 130000, "Feudal Age", new Resources(0, 500, 0, 0));
        public static Research RESEARCH_CASTLE_AGE = new Research(102, 160000, "Castle Age", new Resources(0, 800, 200, 0));
        public static Research RESEARCH_IMPERIAL_AGE = new Research(103, 190000, "Imperial Age", new Resources(0, 1000, 800, 0));
        public static Research RESEARCH_GUARD_TOWER = new Research(140, 30000, "Guard Tower", new Resources(250, 100, 0, 0));
        public static Research RESEARCH_GOLD_SHAFT_MINING = new Research(182, 75000, "Gold Shaft Mining", new Resources(150, 200, 0, 0));
        public static Research RESEARCH_FORTIFIED_WALL = new Research(194, 50000, "Fortified Wall", new Resources(100, 200, 0, 0));
        public static Research RESEARCH_FLETCHING = new Research(199, 30000, "Fletching", new Resources(0, 100, 50, 0));
        public static Research RESEARCH_BODKIN_ARROW = new Research(200, 35000, "Bodkin Arrow", new Resources(0, 200, 100, 0));
        public static Research RESEARCH_BRACER = new Research(201, 40000, "Bracer", new Resources(0, 300, 200, 0));
        public static Research RESEARCH_DOUBLE_BIT_AXE = new Research(202, 25000, "Double-Bit Axe", new Resources(50, 100, 0, 0));
        public static Research RESEARCH_BOW_SAW = new Research(203, 50000, "Bow Saw", new Resources(100, 150, 0, 0));
        public static Research RESEARCH_LONG_SWORDSMAN = new Research(207, 45000, "Long Swordsman", new Resources(0, 200, 65, 0));
        public static Research RESEARCH_CALVALIER = new Research(209, 100000, "Cavalier", new Resources(0, 300, 300, 0));
        public static Research RESEARCH_PADDED_ARCHER_ARMOR = new Research(211, 40000, "Padded Archer Armor", new Resources(0, 100, 0, 0));
        public static Research RESEARCH_LEATHER_ARCHER_ARMOR = new Research(212, 55000, "Leather Archer Armor", new Resources(0, 150, 150, 0));
        public static Research RESEARCH_WHEELBARROW = new Research(213, 75000, "Wheelbarrow", new Resources(50, 175, 0, 0));
        public static Research RESEARCH_SQUIRES = new Research(215, 40000, "Squires", new Resources(0, 100, 0, 0));
        public static Research RESEARCH_TWO_HANDED_SWORDSMAN = new Research(217, 75000, "Two-Handed Swordsman", new Resources(0, 300, 100, 0));
        public static Research RESEARCH_HEAVY_CALVARY_ARCHER = new Research(218, 50000, "Heavy Calvary Archer", new Resources(0, 900, 500, 0));
        public static Research RESEARCH_RING_ARCHER_ARMOR = new Research(219, 70000, "Ring Archer Armor", new Resources(0, 250, 250, 0));
        public static Research RESEARCH_TWO_MAN_SAW = new Research(221, 100000, "Two Man Saw", new Resources(200, 300, 0, 0));
        public static Research RESEARCH_MAN_AT_ARMS = new Research(222, 40000, "Man-at-Arms", new Resources(0, 100, 40, 0));
        public static Research RESEARCH_BLOCK_PRINTING_2 = new Research(230, 55000, "Block Printing", new Resources(0, 0, 200, 0));
        public static Research RESEARCH_SANCTITY = new Research(231, 60000, "Sanctity", new Resources(0, 0, 120, 0));
        public static Research RESEARCH_ILLUMINATION = new Research(233, 65000, "Illumination", new Resources(0, 0, 120, 0));
        public static Research RESEARCH_HEAVY_CAMEL = new Research(236, 105000, "Heavy Camel", new Resources(0, 325, 360, 0));
        public static Research REASEARCH_ARBALEST = new Research(237, 50000, "Arbalest", new Resources(0, 350, 300, 0));
        public static Research RESEARCH_HEAVY_SCORPION = new Research(239, 50000, "Heavy Scorpion", new Resources(1100, 1000, 0, 0));
        public static Research RESEARCH_HEAVY_DEMOLITION_SHIP = new Research(244, 50000, "Heavy Demolition Ship", new Resources(200, 0, 300, 0));
        public static Research RESEARCH_FAST_FIRE_SHIP = new Research(246, 50000, "Fast Fire Ship", new Resources(280, 0, 250, 0));
        public static Research RESEARCH_HAND_CART = new Research(249, 55000, "Hand Cart", new Resources(200, 300, 0, 0));
        public static Research RESEARCH_FERVOR = new Research(252, 50000, "Fervor", new Resources(0, 0, 140, 0));
        public static Research RESEARCH_LIGHT_CALVARY = new Research(254, 45000, "Light Calvary", new Resources(0, 150, 50, 0));
        public static Research RESEARCH_SIEGE_RAM = new Research(255, 75000, "Siege Ram", new Resources(0, 1000, 0, 0));
        public static Research RESEARCH_ONAGER = new Research(257, 75000, "Onager", new Resources(0, 800, 500, 0));
        public static Research RESEARCH_CHAMPION = new Research(264, 100000, "Champion", new Resources(0, 750, 350, 0));
        public static Research RESEARCH_PALADIN = new Research(265, 170000, "Paladin", new Resources(0, 1300, 750, 0));
        public static Research RESEARCH_STONE_MINING = new Research(278, 30000, "Stone Mining", new Resources(75, 100, 0, 0));
        public static Research RESEARCH_STONE_SHAFT_MINING = new Research(279, 75000, "Stone Shaft Mining", new Resources(150, 200, 0, 0));
        public static Research RESEARCH_TOWN_PATROL = new Research(280, 40000, "Town Patrol", new Resources(0, 300, 100, 0));
        public static Research RESEARCH_CONSCRIPTION = new Research(315, 60000, "Conscription", new Resources(0, 150, 150, 0));
        public static Research RESEARCH_REDEMPTION = new Research(316, 50000, "Redemption", new Resources(0, 0, 475, 0));
        public static Research RESEARCH_ATONEMENT = new Research(319, 55000, "Atonement", new Resources(0, 0, 325, 0));
        public static Research RESEARCH_SIEGE_ONAGER = new Research(320, 150000, "Siege Onager", new Resources(0, 1450, 1000, 0));
        public static Research RESEARCH_SAPPERS = new Research(321, 10000, "Sappers", new Resources(0, 400, 200, 0));
        public static Research RESEARCH_MURDER_HOLES = new Research(322, 60000, "Murder Holes", new Resources(0, 200, 0, 100));
        public static Research RESEARCH_ELITE_LONGBOWMAN = new Research(360, 60000, "Elite Longbowman", new Resources(0, 850, 850, 0));
        public static Research RESEARCH_ELITE_CATAPHRACT = new Research(361, 50000, "Elite Cataphract", new Resources(0, 1600, 800, 0));
        public static Research RESEARCH_ELITE_CHU_KO_NU = new Research(362, 50000, "Elite Chu Ko Nu", new Resources(0, 760, 760, 0));
        public static Research RESEARCH_ELITE_THROWING_AXEMAN = new Research(363, 45000, "Elite Throwing Axeman", new Resources(0, 1000, 750, 0));
        public static Research RESEARCH_ELITE_TEUTONIC_KNIGHT = new Research(364, 50000, "Elite Teutonic Knight", new Resources(0, 1200, 600, 0));
        public static Research RESEARCH_ELITE_HUSKARL = new Research(365, 40000, "Elite Huskarl", new Resources(0, 1200, 550, 0));
        public static Research RESEARCH_ELITE_SAMURAI = new Research(366, 60000, "Elite Samurai", new Resources(0, 950, 875, 0));
        public static Research RESEARCH_ELITE_WAR_ELEPHANT = new Research(367, 75000, "Elite War Elephant", new Resources(0, 1600, 1200, 0));
        public static Research RESEARCH_ELITE_MAMELUKE = new Research(368, 50000, "Elite Mameluke", new Resources(0, 600, 500, 0));
        public static Research RESEARCH_ELITE_JANISSARY = new Research(369, 55000, "Elite Janissary", new Resources(0, 850, 750, 0));
        public static Research RESEARCH_ELITE_WOAD_RAIDER = new Research(370, 45000, "Elite Woad Raider", new Resources(0, 1000, 800, 0));
        public static Research RESEARCH_ELITE_MANGUDAI = new Research(371, 50000, "Elite Mangudai", new Resources(0, 1100, 675, 0));
        public static Research RESEARCH_ELITE_LONGBOAT = new Research(372, 60000, "Elite Longboat", new Resources(0, 750, 475, 0));
        public static Research RESEARCH_SHIPWRIGHT = new Research(373, 60000, "Shipwright", new Resources(0, 1000, 300, 0));
        public static Research RESEARCH_CAREENING = new Research(374, 50000, "Careening", new Resources(0, 250, 150, 0));
        public static Research RESEARCH_DRY_DOCK = new Research(375, 60000, "Dry Dock", new Resources(0, 600, 400, 0));
        public static Research RESEARCH_ELITE_CANNON_GALLEON = new Research(376, 30000, "Elite Cannon Galleon", new Resources(525, 0, 500, 0));
        public static Research RESEARCH_SIEGE_ENGINEERS = new Research(377, 45000, "Siege Engineers", new Resources(600, 500, 0, 0));
        public static Research RESEARCH_HOARDINGS = new Research(378, 75000, "Hoardings", new Resources(0, 400, 200, 0));
        public static Research RESEARCH_HEATED_SHOT = new Research(379, 30000, "Heated Shot", new Resources(0, 350, 100, 0));
        public static Research RESEARCH_EAGLE_WARRIOR = new Research(380, 50000, "Eagle Warrior", new Resources(0, 200, 200, 0));
        public static Research RESEARCH_ELITE_BERSERK = new Research(384, 45000, "Elite Berserk", new Resources(0, 1300, 550, 0));
        public static Research RESEARCH_SPIES = new Research(408, 1000, "Spies", new Resources(0, 0, 200, 0));
        public static Research RESEARCH_HUSSAR = new Research(428, 50000, "Hussar", new Resources(0, 500, 600, 0));
        public static Research RESEARCH_HALBERDIER = new Research(429, 50000, "Halberdier", new Resources(0, 300, 600, 0));
        public static Research RESEARCH_ELITE_JAGUAR_WARRIOR = new Research(432, 45000, "Elite Jaguar Warrior", new Resources(0, 1000, 500, 0));
        public static Research RESEARCH_ELITE_EAGLE_WARRIOR = new Research(434, 50000, "Elite Eagle Warrior", new Resources(0, 800, 500, 0));
        public static Research RESEARCH_BLOODLINES = new Research(435, 50000, "Bloodlines", new Resources(0, 150, 100, 0));
        public static Research RESEARCH_PARTHIAN_TACTICS = new Research(436, 65000, "Parthian Tactics", new Resources(0, 200, 250, 0));
        public static Research RESEARCH_THUMB_RING = new Research(437, 45000, "Thumb Ring", new Resources(250, 300, 0, 0));
        public static Research RESEARCH_THEOCRACY = new Research(438, 75000, "Theocracy", new Resources(0, 0, 200, 0));
        public static Research RESEARCH_HERESY = new Research(439, 60000, "Heresy", new Resources(0, 0, 1000, 0));
        public static Research RESEARCH_SUPERMACY = new Research(440, 60000, "Supermacy", new Resources(0, 400, 250, 0));
        public static Research RESEARCH_HERBAL_MEDICINE = new Research(441, 35000, "Herbal Medicine", new Resources(0, 0, 350, 0));
        public static Research RESEARCH_SHINKICHON = new Research(445, 60000, "Shinkichon", new Resources(0, 800, 500, 0));
        public static Research RESEARCH_ELITE_TURTLE_SHIP = new Research(448, 65000, "Elite Turtle Ship", new Resources(0, 1000, 800, 0));
        public static Research RESEARCH_ELIRE_WAR_WAGON = new Research(450, 75000, "Elite War Wagon", new Resources(0, 1000, 800, 0));
        public static Research RESEARCH_PERFUSION = new Research(457, 40000, "Perfusion", new Resources(0, 400, 600, 0));
        public static Research RESEARCH_ATLATL = new Research(460, 40000, "Atlatl", new Resources(0, 400, 350, 0));
        public static Research RESEARCH_WARWOLF = new Research(461, 40000, "Warwolf", new Resources(500, 0, 250, 0));
        public static Research RESEARCH_GREAT_WALL = new Research(462, 40000, "Great Wall", new Resources(400, 0, 0, 200));
        public static Research RESEARCH_CHIEFTANS = new Research(463, 40000, "Chieftans", new Resources(0, 400, 300, 0));
        public static Research RESEARCH_GREEK_FIRE = new Research(464, 40000, "Greek Fire", new Resources(0, 250, 300, 0));
        public static Research RESEARCH_ELITE_GENOESE_CROSSBOWMAN = new Research(468, 60000, "Elite Genoese Crossbowman", new Resources(0, 900, 750, 0));
        public static Research RESEARCH_ELITE_MAGYAR_HUSZAR = new Research(472, 60000, "Elite Magyar Huszar", new Resources(0, 800, 600, 0));
        public static Research RESEARCH_ELITE_ELEPHANT_ARCHER = new Research(481, 60000, "Elite Elephant Archer", new Resources(0, 1000, 800, 0));
        public static Research RESEARCH_STRONGHOLD = new Research(482, 30000, "Stronghold", new Resources(0, 250, 200, 0));
        public static Research RESEARCH_MARAUDERS = new Research(482, 40000, "Marauders", new Resources(300, 0, 200, 0));
        public static Research RESEARCH_YASAMA = new Research(484, 40000, "Yasama", new Resources(300, 300, 0, 0));
        public static Research RESEARCH_OBSIDIAN_ARROWS = new Research(485, 40000, "Obsidian Arrows", new Resources(0, 300, 300, 0));
        public static Research RESEARCH_PANOKSEON = new Research(486, 40000, "Panokseon", new Resources(300, 300, 0, 0));
        public static Research RESEARCH_NOMAD = new Research(487, 40000, "Noamd", new Resources(300, 0, 150, 0));
        public static Research RESEARCH_BOILING_OIL = new Research(488, 40000, "Boiling Oil", new Resources(200, 0, 0, 100));
        public static Research RESEARCH_IRONCLAD = new Research(489, 60000, "Ironclad", new Resources(400, 0, 350, 0));
        public static Research RESEARCH_MADRASAH = new Research(490, 30000, "Madrasah", new Resources(0, 200, 100, 0));
        public static Research RESEARCH_SIPHAI = new Research(491, 60000, "Siphai", new Resources(0, 350, 150, 0));
        public static Research RESEARCH_INQUISITION = new Research(492, 40000, "Inquisition", new Resources(0, 100, 300, 0));
        public static Research RESEARCH_CHIVALRY = new Research(493, 40000, "Chivalry", new Resources(400, 0, 400, 0));
        public static Research RESEARCH_PAVISE = new Research(494, 40000, "Pavise", new Resources(0, 300, 150, 0));
        public static Research RESEARCH_SILK_ROAD = new Research(499, 60000, "Silk Road", new Resources(0, 500, 250, 0));
        public static Research RESEARCH_ELITE_BOYAR = new Research(504, 60000, "Elite Boyar", new Resources(0, 1000, 600, 0));
        public static Research RESEARCH_SULTANS = new Research(506, 40000, "Sultans", new Resources(400, 400, 0, 0));
        public static Research RESEARCH_SHATAGNI = new Research(507, 40000, "Shatagni", new Resources(0, 500, 300, 0));
        public static Research RESEARCH_ELITE_KAMAYUK = new Research(509, 45000, "Elite Kamayuk", new Resources(0, 900, 500, 0));
        public static Research RESEARCH_ORTHODOXY = new Research(512, 40000, "Orthodoxy", new Resources(0, 200, 300, 0));
        public static Research RESEARCH_DRUZHINA = new Research(513, 40000, "Druzhina", new Resources(0, 1200, 500, 0));
        public static Research RESEARCH_MERCENARIES = new Research(514, 40000, "Mercenaries", new Resources(0, 200, 300, 0));
        public static Research RESEARCH_RECURSIVE_BOW = new Research(515, 40000, "Recursive Bow", new Resources(0, 600, 400, 0));
        public static Research RESEARCH_ANDEAN_SLING = new Research(516, 40000, "Andean Sling", new Resources(0, 300, 200, 0));
        public static Research RESEARCH_COURIERS = new Research(517, 40000, "Couriers", new Resources(0, 400, 200, 0));
        public static Research RESEARCH_IMPERIAL_CAMEL = new Research(521, 125000, "Imperial Camel", new Resources(0, 1200, 600, 0));
        //public static Research RESEARCH_HUNTING_DOGS = new Research(526, 15000, "Hunting Dogs");
        public static Research RESEARCH_ELITE_ORGAN_GUN = new Research(563, 45000, "Elite Organ Gun", new Resources(0, 1200, 500, 0));
        public static Research RESEARCH_ELITE_CAMEL_ARCHER = new Research(565, 45000, "Elite Camel Archer", new Resources(1000, 0, 500, 0));
        public static Research RESEARCH_ELITE_GBETO = new Research(567, 45000, "Elite Gbeto", new Resources(0, 900, 600, 0));
        public static Research RESEARCH_ELITE_SHOTEL_WARRIOR = new Research(569, 45000, "Elite Shotel Warrior", new Resources(0, 1200, 550, 0));
        public static Research RESEARCH_CARRACK = new Research(572, 40000, "Carrack", new Resources(200, 0, 300, 0));
        public static Research RESEARCH_ARQUEBUS = new Research(573, 40000, "Arquebus", new Resources(0, 700, 400, 0));
        public static Research RESEARCH_ROYAL_HEIRS = new Research(574, 40000, "Royal Heirs", new Resources(0, 300, 300, 0));
        public static Research RESEARCH_TORSION_ENGINES = new Research(575, 40000, "Torsion Engines", new Resources(0, 1000, 600, 0));
        public static Research RESEARCH_TIGUI = new Research(576, 40000, "Tigui", new Resources(300, 200, 0, 0));
        public static Research RESEARCH_FARIMBA = new Research(577, 40000, "Farimba", new Resources(0, 650, 400, 0));
        public static Research RESEARCH_KASBAH = new Research(578, 40000, "Kasbah", new Resources(0, 250, 250, 0));
        public static Research RESEASRCH_MAGHRABI_CAMELS = new Research(579, 40000, "Maghrabi Camels", new Resources(0, 700, 300, 0));
        public static Research RESEARCH_ELITE_CARAVEL = new Research(597, 60000, "Elite Caravel", new Resources(0, 750, 475, 0));
        public static Research RESEARCH_ELITE_GENITOUR = new Research(599, 60000, "Elite Genitour", new Resources(450, 500, 0, 0));
        public static Research RESEARCH_ARSON = new Research(602, 25000, "Arson", new Resources(0, 150, 50, 0));
        public static Research RESEARCH_ARROWSLITS = new Research(608, 25000, "Arrowslits", new Resources(250, 250, 0, 0));
        public static Research RESEARCH_ELITE_BALLISTA_ELEPHANT = new Research(615, 70000, "Elite Ballista Elephant", new Resources(0, 1000, 500, 0));
        public static Research RESEARCH_ELITE_KARAMBIT_WARRIOR = new Research(617, 40000, "Elite Karambit Warrior", new Resources(0, 900, 600, 0));
        public static Research RESEARCH_ELITE_ARAMBAI = new Research(619, 65000, "Elite Arambai", new Resources(0, 1100, 675, 0));
        public static Research RESEARCH_ELITE_RATTAN_ARCHER = new Research(621, 45000, "Elite Rattan Archer", new Resources(0, 1000, 750, 0));
        public static Research RESEARCH_TUSK_SWORDS = new Research(622, 40000, "Tusk Swords", new Resources(200, 0, 300, 0));
        public static Research RESEARCH_DOUBLE_CROSSBOW = new Research(623, 40000, "Double Crossbow", new Resources(0, 700, 400, 0));
        public static Research RESEARCH_THALASSOCRACY = new Research(624, 40000, "Thalassocracy", new Resources(0, 300, 300, 0));
        public static Research RESEARCH_FORCED_LEVY = new Research(625, 40000, "Forced Levy", new Resources(0, 1000, 600, 0));
        public static Research RESEARCH_HOWDAH = new Research(626, 40000, "Howdah", new Resources(300, 200, 0, 0));
        public static Research RESEARCH_MANIPUR_CALVARY = new Research(627, 40000, "Manipur Calvary", new Resources(0, 650, 400, 0));
        public static Research RESEARCH_CHATRAS = new Research(628, 40000, "Chatras", new Resources(0, 250, 250, 0));
        public static Research RESEARCH_PAPER_MONEY = new Research(629, 40000, "Paper Money", new Resources(0, 800, 200, 0));
        public static Research RESEARCH_ELITE_BATTLE_ELEPHANT = new Research(632, 80000, "Elite Battle Elephant", new Resources(0, 800, 500, 0));
        public static Research RESEARCH_IMPERIAL_SKIRMISHER = new Research(655, 50000, "Imperial Skirmisher", new Resources(200, 0, 100, 0));


        /**
         * Feudal age research ID.
         *
         * @var int
         */
        public const int RESEARCH_FEUDAL = 101;
        /**
         * Castle age research ID.
         *
         * @var int
         */
        public const int RESEARCH_CASTLE = 102;
        /**
         * Imperial age research ID.
         *
         * @var int
         */
        public const int RESEARCH_IMPERIAL = 103;

        public const int FEUDAL_DURATION = 130000;

        public const int CASTLE_DURATION = 160000;

        public const int IMPERIAL_DURATION = 190000;

        public static List<Research> getAllResearch()
        {
            List<Research> list = new List<Research>();
			list.Add(RESEARCH_ELITE_TARKAN);
			list.Add(RESEARCH_YEOMAN);
			list.Add(RESEARCH_EL_DORADO);
			list.Add(RESEARCH_FUROR_CELTICA);
			list.Add(RESEARCH_DRILL);
			list.Add(RESEARCH_MAHOUTS);
			list.Add(RESEARCH_TOWN_WATCH);
			list.Add(RESEARCH_ZEALOTRY);
			list.Add(RESEARCH_ARTILLERY);
			list.Add(RESEARCH_CRENELLATIONS);
			list.Add(RESEARCH_CROP_ROTATION);
			list.Add(RESEARCH_HEAVY_PLOW);
			list.Add(RESEARCH_HEAVY_COLLAR);
			list.Add(RESEARCH_GUILDS);
			list.Add(RESEARCH_ANARCHY);
			list.Add(RESEARCH_BANKING);
			list.Add(RESEARCH_CARTOGRAPHY);
			list.Add(RESEARCH_ATHEISM);
			list.Add(RESEARCH_LOOM);
			list.Add(RESEARCH_COINAGE);
			list.Add(RESEARCH_GARLAND_WARS);
			list.Add(RESEARCH_ELITE_PLUMED_ARCHER);
			list.Add(RESEARCH_WAR_GALLEY);
			list.Add(RESEARCH_GALLEON);
			list.Add(RESEARCH_CANNON_GALLEON);
			list.Add(RESEARCH_HUSBANDRY);
			list.Add(RESEARCH_FAITH);
			list.Add(RESEARCH_BLOCK_PRINTING);
			list.Add(RESEARCH_CHEMISTRY);
			list.Add(RESEARCH_CARAVAN);
			list.Add(RESEARCH_BERSERKERGANG);
			list.Add(RESEARCH_MASONARY);
			list.Add(RESEARCH_ARCHITECTURE);
			list.Add(RESEARCH_ROCKETRY);
			list.Add(RESEARCH_TREADMILL_CRANE);
			list.Add(RESEARCH_GOLD_MINING);
			list.Add(RESEARCH_KATAPARUTO);
			list.Add(RESEARCH_ELITE_CONQUISTADOR);
			list.Add(RESEARCH_LOGISTICA);
			list.Add(RESEARCH_KEEP);
			list.Add(RESEARCH_BOMBARD_TOWER);
			list.Add(RESEARCH_GILLNETS);
			list.Add(RESEARCH_FORGING);
			list.Add(RESEARCH_IRON_CASTING);
			list.Add(RESEARCH_SCALE_MAIL_ARMOR);
			list.Add(RESEARCH_BLAST_FURNACE);
			list.Add(RESEARCH_CHAIN_MAIL_ARMOR);
			list.Add(RESEARCH_PLATE_MAIL_ARMOR);
			list.Add(RESEARCH_PLATE_BARDING_ARMOR);
			list.Add(RESEARCH_SCALE_BARDING_ARMOR);
			list.Add(RESEARCH_CHAIN_BARDING_ARMOR);
			list.Add(RESEARCH_BEARDED_AXE);
			list.Add(RESEARCH_TRACKING);
			list.Add(RESEARCH_BALLISTICS);
			list.Add(RESEARCH_CAPPED_RAM);
			list.Add(RESEARCH_ELITE_SKIRMISHER);
			list.Add(RESEARCH_CROSSBOWMAN);
			list.Add(RESEARCH_FEUDAL_AGE);
			list.Add(RESEARCH_CASTLE_AGE);
			list.Add(RESEARCH_IMPERIAL_AGE);
			list.Add(RESEARCH_GUARD_TOWER);
			list.Add(RESEARCH_GOLD_SHAFT_MINING);
			list.Add(RESEARCH_FORTIFIED_WALL);
			list.Add(RESEARCH_FLETCHING);
			list.Add(RESEARCH_BODKIN_ARROW);
			list.Add(RESEARCH_BRACER);
			list.Add(RESEARCH_DOUBLE_BIT_AXE);
			list.Add(RESEARCH_BOW_SAW);
			list.Add(RESEARCH_LONG_SWORDSMAN);
			list.Add(RESEARCH_CALVALIER);
			list.Add(RESEARCH_PADDED_ARCHER_ARMOR);
			list.Add(RESEARCH_LEATHER_ARCHER_ARMOR);
			list.Add(RESEARCH_WHEELBARROW);
			list.Add(RESEARCH_SQUIRES);
			list.Add(RESEARCH_TWO_HANDED_SWORDSMAN);
			list.Add(RESEARCH_HEAVY_CALVARY_ARCHER);
			list.Add(RESEARCH_RING_ARCHER_ARMOR);
			list.Add(RESEARCH_TWO_MAN_SAW);
			list.Add(RESEARCH_MAN_AT_ARMS);
			list.Add(RESEARCH_BLOCK_PRINTING_2);
			list.Add(RESEARCH_SANCTITY);
			list.Add(RESEARCH_ILLUMINATION);
			list.Add(RESEARCH_HEAVY_CAMEL);
			list.Add(REASEARCH_ARBALEST);
			list.Add(RESEARCH_HEAVY_SCORPION);
			list.Add(RESEARCH_HEAVY_DEMOLITION_SHIP);
			list.Add(RESEARCH_FAST_FIRE_SHIP);
			list.Add(RESEARCH_HAND_CART);
			list.Add(RESEARCH_FERVOR);
			list.Add(RESEARCH_LIGHT_CALVARY);
			list.Add(RESEARCH_SIEGE_RAM);
			list.Add(RESEARCH_ONAGER);
			list.Add(RESEARCH_CHAMPION);
			list.Add(RESEARCH_PALADIN);
			list.Add(RESEARCH_STONE_MINING);
			list.Add(RESEARCH_STONE_SHAFT_MINING);
			list.Add(RESEARCH_TOWN_PATROL);
			list.Add(RESEARCH_CONSCRIPTION);
			list.Add(RESEARCH_REDEMPTION);
			list.Add(RESEARCH_ATONEMENT);
			list.Add(RESEARCH_SIEGE_ONAGER);
			list.Add(RESEARCH_SAPPERS);
			list.Add(RESEARCH_MURDER_HOLES);
			list.Add(RESEARCH_ELITE_LONGBOWMAN);
			list.Add(RESEARCH_ELITE_CATAPHRACT);
			list.Add(RESEARCH_ELITE_CHU_KO_NU);
			list.Add(RESEARCH_ELITE_THROWING_AXEMAN);
			list.Add(RESEARCH_ELITE_TEUTONIC_KNIGHT);
			list.Add(RESEARCH_ELITE_HUSKARL);
			list.Add(RESEARCH_ELITE_SAMURAI);
			list.Add(RESEARCH_ELITE_WAR_ELEPHANT);
			list.Add(RESEARCH_ELITE_MAMELUKE);
			list.Add(RESEARCH_ELITE_JANISSARY);
			list.Add(RESEARCH_ELITE_WOAD_RAIDER);
			list.Add(RESEARCH_ELITE_MANGUDAI);
			list.Add(RESEARCH_ELITE_LONGBOAT);
			list.Add(RESEARCH_SHIPWRIGHT);
			list.Add(RESEARCH_CAREENING);
			list.Add(RESEARCH_DRY_DOCK);
			list.Add(RESEARCH_ELITE_CANNON_GALLEON);
			list.Add(RESEARCH_SIEGE_ENGINEERS);
			list.Add(RESEARCH_HOARDINGS);
			list.Add(RESEARCH_HEATED_SHOT);
			list.Add(RESEARCH_EAGLE_WARRIOR);
			list.Add(RESEARCH_ELITE_BERSERK);
			list.Add(RESEARCH_SPIES);
			list.Add(RESEARCH_HUSSAR);
			list.Add(RESEARCH_HALBERDIER);
			list.Add(RESEARCH_ELITE_JAGUAR_WARRIOR);
			list.Add(RESEARCH_ELITE_EAGLE_WARRIOR);
			list.Add(RESEARCH_BLOODLINES);
			list.Add(RESEARCH_PARTHIAN_TACTICS);
			list.Add(RESEARCH_THUMB_RING);
			list.Add(RESEARCH_THEOCRACY);
			list.Add(RESEARCH_HERESY);
			list.Add(RESEARCH_SUPERMACY);
			list.Add(RESEARCH_HERBAL_MEDICINE);
			list.Add(RESEARCH_SHINKICHON);
			list.Add(RESEARCH_ELITE_TURTLE_SHIP);
			list.Add(RESEARCH_ELIRE_WAR_WAGON);
			list.Add(RESEARCH_PERFUSION);
			list.Add(RESEARCH_ATLATL);
			list.Add(RESEARCH_WARWOLF);
			list.Add(RESEARCH_GREAT_WALL);
			list.Add(RESEARCH_CHIEFTANS);
			list.Add(RESEARCH_GREEK_FIRE);
			list.Add(RESEARCH_ELITE_GENOESE_CROSSBOWMAN);
			list.Add(RESEARCH_ELITE_MAGYAR_HUSZAR);
			list.Add(RESEARCH_ELITE_ELEPHANT_ARCHER);
			list.Add(RESEARCH_STRONGHOLD);
			list.Add(RESEARCH_MARAUDERS);
			list.Add(RESEARCH_YASAMA);
			list.Add(RESEARCH_OBSIDIAN_ARROWS);
			list.Add(RESEARCH_PANOKSEON);
			list.Add(RESEARCH_NOMAD);
			list.Add(RESEARCH_BOILING_OIL);
			list.Add(RESEARCH_IRONCLAD);
			list.Add(RESEARCH_MADRASAH);
			list.Add(RESEARCH_SIPHAI);
			list.Add(RESEARCH_INQUISITION);
			list.Add(RESEARCH_CHIVALRY);
			list.Add(RESEARCH_PAVISE);
			list.Add(RESEARCH_SILK_ROAD);
			list.Add(RESEARCH_ELITE_BOYAR);
			list.Add(RESEARCH_SULTANS);
			list.Add(RESEARCH_SHATAGNI);
			list.Add(RESEARCH_ELITE_KAMAYUK);
			list.Add(RESEARCH_ORTHODOXY);
			list.Add(RESEARCH_DRUZHINA);
			list.Add(RESEARCH_MERCENARIES);
			list.Add(RESEARCH_RECURSIVE_BOW);
			list.Add(RESEARCH_ANDEAN_SLING);
			list.Add(RESEARCH_COURIERS);
			list.Add(RESEARCH_IMPERIAL_CAMEL);
			//list.Add(RESEARCH_HUNTING_DOGS);
			list.Add(RESEARCH_ELITE_ORGAN_GUN);
			list.Add(RESEARCH_ELITE_CAMEL_ARCHER);
			list.Add(RESEARCH_ELITE_GBETO);
			list.Add(RESEARCH_ELITE_SHOTEL_WARRIOR);
			list.Add(RESEARCH_CARRACK);
			list.Add(RESEARCH_ARQUEBUS);
			list.Add(RESEARCH_ROYAL_HEIRS);
			list.Add(RESEARCH_TORSION_ENGINES);
			list.Add(RESEARCH_TIGUI);
			list.Add(RESEARCH_FARIMBA);
			list.Add(RESEARCH_KASBAH);
			list.Add(RESEASRCH_MAGHRABI_CAMELS);
			list.Add(RESEARCH_ELITE_CARAVEL);
			list.Add(RESEARCH_ELITE_GENITOUR);
			list.Add(RESEARCH_ARSON);
			list.Add(RESEARCH_ARROWSLITS);
			list.Add(RESEARCH_ELITE_BALLISTA_ELEPHANT);
			list.Add(RESEARCH_ELITE_KARAMBIT_WARRIOR);
			list.Add(RESEARCH_ELITE_ARAMBAI);
			list.Add(RESEARCH_ELITE_RATTAN_ARCHER);
			list.Add(RESEARCH_TUSK_SWORDS);
			list.Add(RESEARCH_DOUBLE_CROSSBOW);
			list.Add(RESEARCH_THALASSOCRACY);
			list.Add(RESEARCH_FORCED_LEVY);
			list.Add(RESEARCH_HOWDAH);
			list.Add(RESEARCH_MANIPUR_CALVARY);
			list.Add(RESEARCH_CHATRAS);
			list.Add(RESEARCH_PAPER_MONEY);
			list.Add(RESEARCH_ELITE_BATTLE_ELEPHANT);
			list.Add(RESEARCH_IMPERIAL_SKIRMISHER);

            return list;
		}
    }
}
